version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: oculyze
    ports:
      - 27017:27017
    restart: unless-stopped
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: oculyze
      ME_CONFIG_MONGODB_URL: mongodb://root:oculyze@mongo:27017/
    
networks:
  default:
    external:
      name: oculyze-network